# upgrade_openjdk.yml
---
- name: Upgrade OpenJDK on JBOSS servers
  hosts: JBOSS
  become: yes

  tasks:
    - name: Copy OpenJDK tar file to remote server
      copy:
        src: /path/to/openjdk.tar.gz
        dest: /tmp/openjdk.tar.gz
      delegate_to: "{{ inventory_hostname }}"  # Copy to each host

    - name: Extract OpenJDK tar file
      unarchive:
        src: /tmp/openjdk.tar.gz
        dest: /usr/local/java
        remote_src: yes
      delegate_to: "{{ inventory_hostname }}"  # Extract on each host

    - name: Check old Java version
      shell: java -version 2>&1 | awk '/version/ {print $3}' | sed 's/"//g'
      register: old_java_version
      changed_when: false
      failed_when: false
      delegate_to: "{{ inventory_hostname }}"

    - name: Check new Java version
      shell: /usr/local/java/bin/java -version 2>&1 | awk '/version/ {print $3}' | sed 's/"//g'
      register: new_java_version
      changed_when: false
      failed_when: false
      delegate_to: "{{ inventory_hostname }}"

    - name: Display Java versions
      debug:
        msg: "Old Java version: {{ old_java_version.stdout }} - New Java version: {{ new_java_version.stdout }}"
