---
- name: Upgrade Java Version
  hosts: TRN
  gather_facts: yes

  tasks:
    # Step 1: Copy openjdk tar file from local to server tmp dir
    - name: Copy openjdk tar file to server
      ansible.builtin.copy:
        src: /path/to/your/openjdk.tar.gz
        dest: /tmp/openjdk.tar.gz

    # Step 2: Untar the file in tmp dir
    - name: Untar openjdk tar file
      ansible.builtin.unarchive:
        src: /tmp/openjdk.tar.gz
        dest: /usr/local/  # Change this destination directory as per your requirement
        remote_src: yes
      become: yes

    # Step 3: Check and save current java version
    - name: Check current Java version
      command: java -version
      register: current_java_version
      ignore_errors: true

    - set_fact:
        old_java_version: "{{ current_java_version.stderr | regex_replace('openjdk version \"([0-9]+\\.[0-9]+).*\".*', '\\1') }}"
      when: current_java_version.rc == 0

    # Step 4: Check copied java version
    - name: Check new Java version
      shell: "/usr/local/bin/java -version"
      register: new_java_version
      ignore_errors: true

    - set_fact:
        new_java_version: "{{ new_java_version.stderr | regex_replace('openjdk version \"([0-9]+\\.[0-9]+).*\".*', '\\1') }}"
      when: new_java_version.rc == 0

    # Step 5: Compare old and new java versions
    - name: Check if Java versions match
      ansible.builtin.debug:
        msg: "Java versions are not matching. You can proceed with Java upgrade."
      when: old_java_version != new_java_version
